language: python
python:
  - "3.6"
env:
  - DJANGO_VERSION=1.11.2
  - PROJECT='edc_metadata'

services:
  - mysql

install:
  - pip3 install --upgrade pip setuptools
  - pip3 install -q Django==$DJANGO_VERSION
  - pip3 install flake8
  - pip3 install coveralls
  - pip3 install mysqlclient
  - pip3 install -q -r requirements.txt

before_script:
  - flake8 $PROJECT
  - mysql -e 'create database edc character set utf8;'

script: 
  - coverage run --source=$PROJECT manage.py test

after_success:
  - coveralls
